services:
  migrate:
    build: .
    container_name: cart_migrate
    env_file:
      - .env
    environment:
      - DB_HOST=cart_db
    command: [ "alembic", "upgrade", "head" ]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - shop_network

  app:
    build: .
    container_name: cart_app
    env_file:
      - .env
    environment:
      - DB_HOST=cart_db
    ports:
      - "8003:8003"
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks:
      - shop_network
    restart: unless-stopped

  db:
    image: postgres:18
    container_name: cart_db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - shop_network
    restart: unless-stopped

volumes:
  db_data:


networks:
  shop_network:
    external: true
